all: compile link

compile:
	g++ -Isrc/include -c coding/*.cpp

link:
	g++ -Isrc/include -Icoding/UtilFunctions -Icoding/Widgets/Header -Icoding/Widgets/Source -Icoding -c coding/*.cpp
	g++ *.o -o main -Lsrc/lib -lsfml-graphics -lsfml-window -lsfml-system -lopengl32 -lsfml-audio

	./main.exe





